---
spring:
  application:
    name: MyEurekaServer
    
  
    
    
server:
   port: 8661
   
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8661/eureka/
      
    register-with-eureka: false
    
    fetch-registry: false
    
   
   
  instance:
     prefer-ip-address: true
     


...